name: Check Semver

permissions: {}

on:
    pull_request:
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check-semver:
        name: Check semver
        runs-on: ubuntu-latest
        container:
            image: archlinux:base-devel
        steps:
            - name: Install dependencies
              run: |
                  pacman --noconfirm --needed -Syu \
                    git \
                    rustup \
                    clang \
                    gtk4 \
                    libpulse \
                    fftw \
                    libpipewire \
                    systemd-libs

            - name: Setup Rust
              run: rustup default stable

            - uses: actions/checkout@v6
              with:
                  persist-credentials: false
                  submodules: recursive

            - uses: obi1kenobi/cargo-semver-checks-action@v2
